-- M2B: device registry (metadata only). The human Clerk session registers a device;
-- the scoped device credential arrives with M2C pairing (device_key_id stays NULL now).
CREATE TABLE IF NOT EXISTS devices (
  id              TEXT PRIMARY KEY,
  account_id      TEXT NOT NULL REFERENCES accounts(id),
  -- Random, non-secret per-installation id generated by the desktop. One installation
  -- is bound to exactly one account; automatic reassignment is refused.
  installation_id TEXT NOT NULL UNIQUE,
  type            TEXT NOT NULL CHECK (type IN ('desktop', 'node')),
  platform        TEXT NOT NULL CHECK (platform IN ('darwin', 'win32', 'linux')),
  display_name    TEXT NOT NULL,
  capabilities    TEXT[] NOT NULL DEFAULT '{}',
  device_key_id   TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at    TIMESTAMPTZ,
  revoked_at      TIMESTAMPTZ,
  UNIQUE (account_id, id)
);
CREATE INDEX IF NOT EXISTS devices_account_idx ON devices (account_id);
